print("Flour -" ,var_flour)
print("Butter -" ,var_butter)
print("Sugar -" ,var_sugar)
print("Eggs -" ,var_eggs)
print("Cocoa Powder -" ,var_cocoa_powder)
print("Baking Powder -" ,var_baking_powder)